// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSy6Hg0o3fbsnvQ10DN-MpBMIkrN28qKg',
    appId: '1:727523155877:web:3883225fb49ffef554124c',
    messagingSenderId: '727523155877',
    projectId: 'weatherapp-81b83',
    authDomain: 'weatherapp-81b83.firebaseapp.com',
    storageBucket: 'weatherapp-81b83.appspot.com',
    measurementId: 'G-E4W2KGWT0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrQ8N9j_5ewdsdfeNYNg9DnNUjweHPvPM',
    appId: '1:727523155877:android:0ff524dfd1087dab54124c',
    messagingSenderId: '727523155877',
    projectId: 'weatherapp-81b83',
    storageBucket: 'weatherapp-81b83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnT5R-DWXMd0rrygBYYYscq37RJnURzSM',
    appId: '1:727523155877:ios:5ee19770b849828b54124c',
    messagingSenderId: '727523155877',
    projectId: 'weatherapp-81b83',
    storageBucket: 'weatherapp-81b83.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnT5R-DWXMd0rrygBYYYscq37RJnURzSM',
    appId: '1:727523155877:ios:5ee19770b849828b54124c',
    messagingSenderId: '727523155877',
    projectId: 'weatherapp-81b83',
    storageBucket: 'weatherapp-81b83.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSy6Hg0o3fbsnvQ10DN-MpBMIkrN28qKg',
    appId: '1:727523155877:web:10f5421ca69e491554124c',
    messagingSenderId: '727523155877',
    projectId: 'weatherapp-81b83',
    authDomain: 'weatherapp-81b83.firebaseapp.com',
    storageBucket: 'weatherapp-81b83.appspot.com',
    measurementId: 'G-WHCVXWT3VK',
  );
}
