// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7NlNiPZRiKFVVAT4jd0sSiYkmEjCqWjs',
    appId: '1:818881687846:web:cbd91947944faae5b691e7',
    messagingSenderId: '818881687846',
    projectId: 'weatherapp-774cd',
    authDomain: 'weatherapp-774cd.firebaseapp.com',
    storageBucket: 'weatherapp-774cd.appspot.com',
    measurementId: 'G-9TH2179GN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPqydriK0y-2P-NXazk2Uvomnag9_3Pw4',
    appId: '1:818881687846:android:059e06000de21400b691e7',
    messagingSenderId: '818881687846',
    projectId: 'weatherapp-774cd',
    storageBucket: 'weatherapp-774cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZL6cXZu4cdBZoSog3Nbo5bTtZjG0qTbk',
    appId: '1:818881687846:ios:0ddb5843bb417d6db691e7',
    messagingSenderId: '818881687846',
    projectId: 'weatherapp-774cd',
    storageBucket: 'weatherapp-774cd.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZL6cXZu4cdBZoSog3Nbo5bTtZjG0qTbk',
    appId: '1:818881687846:ios:0ddb5843bb417d6db691e7',
    messagingSenderId: '818881687846',
    projectId: 'weatherapp-774cd',
    storageBucket: 'weatherapp-774cd.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7NlNiPZRiKFVVAT4jd0sSiYkmEjCqWjs',
    appId: '1:818881687846:web:ecfbb480749ac484b691e7',
    messagingSenderId: '818881687846',
    projectId: 'weatherapp-774cd',
    authDomain: 'weatherapp-774cd.firebaseapp.com',
    storageBucket: 'weatherapp-774cd.appspot.com',
    measurementId: 'G-PJ86B9LW8M',
  );

}